import { Airport } from '../types';

export const AIRPORTS: Record<string, Airport> = {
  DEL: {
    code: 'DEL',
    name: 'Indira Gandhi International Airport',
    nameHi: 'इन्दिरा गाँधी अंतर्राष्ट्रीय हवाई अड्डा',
    city: 'New Delhi',
    cityHi: 'नई दिल्ली',
    state: 'Delhi',
    lat: 28.5562,
    lng: 77.1000,
    tier: 1,
  },
  BOM: {
    code: 'BOM',
    name: 'Chhatrapati Shivaji Maharaj International Airport',
    nameHi: 'छत्रपति शिवाजी महाराज अंतर्राष्ट्रीय हवाई अड्डा',
    city: 'Mumbai',
    cityHi: 'मुंबई',
    state: 'Maharashtra',
    lat: 19.0896,
    lng: 72.8656,
    tier: 1,
  },
  BLR: {
    code: 'BLR',
    name: 'Kempegowda International Airport',
    nameHi: 'केम्पेगौड़ा अंतर्राष्ट्रीय हवाई अड्डा',
    city: 'Bengaluru',
    cityHi: 'बेंगलुरु',
    state: 'Karnataka',
    lat: 13.1986,
    lng: 77.7066,
    tier: 1,
  },
  HYD: {
    code: 'HYD',
    name: 'Rajiv Gandhi International Airport',
    nameHi: 'राजीव गाँधी अंतर्राष्ट्रीय हवाई अड्डा',
    city: 'Hyderabad',
    cityHi: 'हैदराबाद',
    state: 'Telangana',
    lat: 17.2403,
    lng: 78.4294,
    tier: 1,
  },
  MAA: {
    code: 'MAA',
    name: 'Chennai International Airport',
    nameHi: 'चेन्नई अंतर्राष्ट्रीय हवाई अड्डा',
    city: 'Chennai',
    cityHi: 'चेन्नई',
    state: 'Tamil Nadu',
    lat: 12.9941,
    lng: 80.1709,
    tier: 1,
  },
  CCU: {
    code: 'CCU',
    name: 'Netaji Subhash Chandra Bose International Airport',
    nameHi: 'नेताजी सुभाष चंद्र बोस अंतर्राष्ट्रीय हवाई अड्डा',
    city: 'Kolkata',
    cityHi: 'कोलकाता',
    state: 'West Bengal',
    lat: 22.6547,
    lng: 88.4467,
    tier: 1,
  },
  AMD: {
    code: 'AMD',
    name: 'Sardar Vallabhbhai Patel International Airport',
    nameHi: 'सरदार वल्लभभाई पटेल अंतर्राष्ट्रीय हवाई अड्डा',
    city: 'Ahmedabad',
    cityHi: 'अहमदाबाद',
    state: 'Gujarat',
    lat: 23.0726,
    lng: 72.6347,
    tier: 1,
  },
  PNQ: {
    code: 'PNQ',
    name: 'Pune International Airport',
    nameHi: 'पुणे अंतर्राष्ट्रीय हवाई अड्डा',
    city: 'Pune',
    cityHi: 'पुणे',
    state: 'Maharashtra',
    lat: 18.5822,
    lng: 73.9197,
    tier: 2,
  },
  GOI: {
    code: 'GOI',
    name: 'Dabolim Airport / Goa International Airport',
    nameHi: 'गोवा डाबोलिम हवाई अड्डा',
    city: 'Goa',
    cityHi: 'गोवा',
    state: 'Goa',
    lat: 15.3808,
    lng: 73.8314,
    tier: 2,
  },
  COK: {
    code: 'COK',
    name: 'Cochin International Airport',
    nameHi: 'कोचीन अंतर्राष्ट्रीय हवाई अड्डा',
    city: 'Kochi',
    cityHi: 'कोच्चि',
    state: 'Kerala',
    lat: 10.1518,
    lng: 76.3930,
    tier: 2,
  },
  LKO: {
    code: 'LKO',
    name: 'Chaudhary Charan Singh International Airport',
    nameHi: 'चौधरी चरण सिंह अंतर्राष्ट्रीय हवाई अड्डा',
    city: 'Lucknow',
    cityHi: 'लखनऊ',
    state: 'Uttar Pradesh',
    lat: 26.7606,
    lng: 80.8893,
    tier: 2,
  },
  JAI: {
    code: 'JAI',
    name: 'Jaipur International Airport',
    nameHi: 'जयपुर अंतर्राष्ट्रीय हवाई अड्डा',
    city: 'Jaipur',
    cityHi: 'जयपुर',
    state: 'Rajasthan',
    lat: 26.8286,
    lng: 75.8056,
    tier: 2,
  },
  GAU: {
    code: 'GAU',
    name: 'Lokpriya Gopinath Bordoloi International Airport',
    nameHi: 'लोकप्रिय गोपीनाथ बोरदोलोई अंतर्राष्ट्रीय हवाई अड्डा',
    city: 'Guwahati',
    cityHi: 'गुवाहाटी',
    state: 'Assam',
    lat: 26.1061,
    lng: 91.5859,
    tier: 2,
  },
};

export const AIRPORT_LIST = Object.values(AIRPORTS);
